name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js 16.15.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
      - name: Install dependencies
        run: npm ci
      - name: TypeScript typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
